### ISSUE TITLE
[妄想] lint設定の別リポジトリ化

### ISSUE THREAD

**Issue by kaave** [framelunch/scaffold-frontend#2]
## 内容

eslintとstylelintの設定をそれぞれ独立したリポジトリに切り出したほうがいい気がしてきた。
うまくいったらphpmdとかswiftlintも。できるのかはわかんない

## 目的

- 各プロジェクトでかぶりまくってるのでコアな設定を一箇所にまとめたい
- 設定のみをバージョン管理したい
- lint設定について議論とかできるように
- **package.jsonすっきりさせたい(ESLintとかairbnbのからみで最悪にややこしい)**
- **lintのセットアップをシンプルにしたい**

## 手順

**コマンドはうろ覚えなので怪しい**

- framelunch/fl-lint-config-eslint
- framelunch/fl-lint-config-stylelint
- framelunch/fl-lint-config-stylelint-scss

みたいな形にしておいて、
`yarn add -D git+https://github.com/framelunch/fl-lint-config-eslint`
`yarn add -D git+https://github.com/framelunch/fl-lint-config-stylelint`
って具合で各プロジェクトに入れる。

設定は結構マメにバージョンを切るようにして、なんでエラーになったんや〜が起きないように。
`yarn add -D git+https://github.com/framelunch/fl-lint-config-stylelint#v1.0.0`
みたいな感じで入れる際にバージョン指定できたはず。

**Comment by kaave** [comment]
ESLintとstylelintともにとりあえずできた。

**Comment by pond6** [comment]
遅くなりましたが、のちほど確認させていただきます

**Comment by pond6** [comment]
これはとても良い管理方法だと思う。そしてgitからnode_moduleに追加できるということは初めて知りました。

**Comment by pond6** [comment]
あれ？lintの方、flow-typed, flow-binがpackage.jsonか消えてるけど間違い？

**Comment by kaave** [comment]
ウッ、勢い良くやってしまった系であります・・・ 😢

**Comment by kaave** [comment]
ちなみに `npm install` ではgit以外にもローカルファイルとかtarとかもいけます。
https://docs.npmjs.com/cli/install
githubとかbitbucketにエイリアスあるのははじめて知りました。いろいろあるなぁ・・・

**Comment by kaave** [comment]
72993b65418d0becff449d737c0a8946a9da3586 で退治
